# Generated by Django 5.2.7 on 2025-10-03 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_path', models.CharField(help_text='The local file path of the repository that was scanned.', max_length=500)),
                ('rule_id', models.CharField(help_text='The Gitleaks rule ID that matched the secret.', max_length=100)),
                ('status', models.CharField(choices=[('PASS', 'Compliance Passed'), ('FAIL', 'Compliance Failed'), ('SKIP', 'Check Skipped')], default='FAIL', max_length=10)),
                ('details', models.TextField(blank=True, help_text='Full technical details or full Gitleaks JSON finding (optional).', null=True)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_latest', models.BooleanField(default=True, help_text='True if this is the most recent check.')),
                ('file_path', models.CharField(help_text='The file path where the secret was found.', max_length=500)),
                ('line_number', models.IntegerField(help_text='The line number.')),
                ('commit_hash', models.CharField(help_text='The SHA-1 hash of the commit.', max_length=40)),
                ('author', models.CharField(help_text='The author of the commit.', max_length=100)),
                ('secret_snippet', models.TextField(help_text='A snippet of the leaked secret.')),
            ],
            options={
                'indexes': [models.Index(fields=['repo_path', 'checked_at'], name='app_checkre_repo_pa_bf9e63_idx')],
            },
        ),
    ]
