# Generated by Django 5.2.7 on 2025-10-03 01:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="A unique name for this target (e.g., 'Prod-S3-Bucket').", max_length=255, unique=True)),
                ('resource_type', models.CharField(help_text="The type of resource being checked (e.g., 'AWS S3', 'GitHub', 'K8s').", max_length=50)),
                ('identifier', models.CharField(help_text='The resource ID or path used by the checker tool.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to exclude this target from future scans.')),
            ],
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(help_text='The name of the policy or check rule that was run.', max_length=100)),
                ('status', models.CharField(choices=[('PASS', 'Compliance Passed'), ('FAIL', 'Compliance Failed'), ('SKIP', 'Check Skipped')], max_length=10)),
                ('details', models.TextField(blank=True, help_text='Technical details on why the check passed or failed.', null=True)),
                ('checked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_latest', models.BooleanField(default=True, help_text='True if this is the most recent check for this policy on this target.')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compliancetarget')),
            ],
        ),
    ]
