# Generated by Django 5.2.7 on 2025-10-03 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkresult',
            name='policy_name',
        ),
        migrations.RemoveField(
            model_name='compliancetarget',
            name='identifier',
        ),
        migrations.AddField(
            model_name='checkresult',
            name='author',
            field=models.CharField(default='unknown', help_text='The author of the commit that introduced the secret.', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkresult',
            name='commit_hash',
            field=models.CharField(default=0, help_text='The SHA-1 hash of the commit that introduced the secret.', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkresult',
            name='file_path',
            field=models.CharField(default='unknown', help_text='The file path in the repository where the secret was found.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkresult',
            name='line_number',
            field=models.IntegerField(default=0, help_text='The line number in the file where the secret was found.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkresult',
            name='rule_id',
            field=models.CharField(default='N/A', help_text="The Gitleaks rule ID that matched the secret (e.g., 'GitHub-Token', 'AWS-Key').", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkresult',
            name='secret_snippet',
            field=models.TextField(default='N/A', help_text='A snippet of the leaked secret (often redacted by Gitleaks).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compliancetarget',
            name='repo_path',
            field=models.CharField(default='unknown', help_text='The local file path or URL of the repository to be scanned by Gitleaks.', max_length=500, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='details',
            field=models.TextField(blank=True, help_text='Full technical details or full Gitleaks JSON finding (optional).', null=True),
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='is_latest',
            field=models.BooleanField(default=True, help_text='True if this is the most recent check for this target.'),
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='status',
            field=models.CharField(choices=[('PASS', 'Compliance Passed'), ('FAIL', 'Compliance Failed'), ('SKIP', 'Check Skipped')], default='FAIL', max_length=10),
        ),
        migrations.AlterField(
            model_name='checkresult',
            name='target',
            field=models.ForeignKey(help_text='The repository that was scanned.', on_delete=django.db.models.deletion.CASCADE, to='app.compliancetarget'),
        ),
        migrations.AlterField(
            model_name='compliancetarget',
            name='name',
            field=models.CharField(help_text="A unique, human-readable name for this target (e.g., 'Core Application Repo').", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='compliancetarget',
            name='resource_type',
            field=models.CharField(default='Git Repository', help_text="The type of resource being checked (e.g., 'Git Repository', 'AWS S3', 'K8s').", max_length=50),
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['target', 'checked_at'], name='app_checkre_target__b81de3_idx'),
        ),
    ]
