# 4. Render Task Definition
      - name: Render Task Definition
        id: render-task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          # Task Definition Family name, matching the prefix
          task-definition: compliance-checker-demo-task 
          # Container Name, matching the prefix
          container-name: compliance-checker-demo-container 
          image: ${{ steps.build-image.outputs.IMAGE_URI }}
          output-task-definition: task-definition.json

      # 5. Deploy the updated Task Definition to the ECS Service
      - name: Deploy to Amazon ECS Service
        uses: aws-actions/amazon-ecs-deploy-service@v1
        with:
          task-definition: task-definition.json
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}